apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-zabbix-webhook-config
  namespace: monitoring
data:
  config-webhook.yaml: |+
    port: 8080
    queueCapacity: 500
    zabbixServerHost: zabbix-server-here.local.com
    zabbixServerPort: 10051
    zabbixHostAnnotation: zabbix
    zabbixKeyPrefix: prometheus
